Screenly/Playground

edge-apps/clock/index.html, edge-apps/clock/static/js/main.js
The display (screen) is not able to display the current time, even if the clock app was uploaded successfully.
=> fix: Have the display show the current time even though some settings are undefined

edge-apps/weather/index.html, edge-apps/weather/screenly.yml
=> Fixes weather app settings

edge-apps/weather/static/js/main.js
```
pi@srly-bp537cnfnp4n5p1:/$ sudo journalctl -f | grep -E "Database failed to open|Database opened successfully|Cannot read property 'transaction' of undefined"
Aug 29 21:08:30 srly-bp537cnfnp4n5p1 screenly-client.viewer[1196]: I20230829 21:08:30.030047  1196 main.cpp:41] [JSLog] TypeError: Cannot read property 'transaction' of undefined
Aug 29 21:08:30 srly-bp537cnfnp4n5p1 screenly-client.viewer[1196]: I20230829 21:08:30.255527  1196 main.cpp:41] [JSLog] Database opened successfully
Aug 29 21:08:49 srly-bp537cnfnp4n5p1 screenly-client.viewer[1196]: I20230829 21:08:49.997946  1196 main.cpp:41] [JSLog] Database opened successfully
```
=> Fixes the weather app not displaying properly.

edge-apps/rss-reader/static/js/main.js
- Adds checking for `screenly.cors_proxy_url`.
=> Fixes CORS issue with the RSS reader app

edge-apps/rss-reader/screenly.yml
| URL                                                 | Requires CORS | bypass_cors |
| --------------------------------------------------- | ------------- | ----------- |
| http://feeds.bbci.co.uk/news/rss.xml                | Yes           | true        |
| https://lifehacker.com/rss                          | Yes           | true        |
| https://www.reddit.com/.rss                         | Yes           | true        |
| https://rss.nytimes.com/services/xml/rss/nyt/US.xml | No            | false       |
| http://rss.sciam.com/sciam/60secsciencepodcast      | Yes           | true        |
Furthermore, you can see a curated list of RSS feeds here &mdash; https://github.com/plenaryapp/awesome-rss-feeds.
=> Applies hotfixes to RSS reader app

edge-apps/asset-metadata/screenly.yml, edge-apps/powerbi/screenly.yml
Edits:
- Fix: screenly.yml for `asset-metadata`. 
Error: 
```
Failed to publish edge app manifest: parse error: Setting "google_maps_api_key" is of type "secret" and cannot have a default value at line 2 column 1
```
- Update:  `optional` parameters in screenly.yml for `powerbi`. I made required those parameters that are required in [docs](https://www.screenly.io/tutorials/powerbi/)
- Update: descriptions for Edge Apps
=> Edits: for Edge Apps after QA

.github/workflows/deploy-clock-app.yml, .github/workflows/deploy-rss-reader.yml, .github/workflows/deploy-weather-app.yml
Edits:
- Fix: deploy workflow for Clock/Weather and RSS reader Edge Apps
Proofs:
- https://github.com/rusko124/playground/actions/runs/7471539798/job/20331998389
- https://github.com/rusko124/playground/actions/runs/7471539795/job/20331998403
- https://github.com/rusko124/playground/actions/runs/7471539793/job/20331998393
Notes:
- Need to set Edge App IDs
=> Fix: deploy workflow for Clock/Weather and RSS reader Edge Apps

edge-apps/weather/screenly.yml, edge-apps/weather/static/js/main.js
Edits:
- Added `override_coordinates` setting that allows to override of screen metadata coordinates.
=> New: override_coordinates setting for Weather Edge App

edge-apps/powerbi/index.html, edge-apps/powerbi/screenly.yml, edge-apps/weather/index.html, edge-apps/weather/screenly.yml
Introduced in Screenly Client version 3.6.1, we can now instruct the device to wait for a wait signal before showing the content on screen. This is the first adoption of this to ensure Power BI loads snappier.
=> Adds wait signal to Power BI Edge App

.github/linters/.yamllint.yml, .github/workflows/linter.yml, edge-apps/iframe/screenly.yml, edge-apps/powerbi/.htmlhintrc, edge-apps/powerbi/index.html, edge-apps/powerbi/screenly.yml
* Allows `report` to be provided as `Report` by enforcing lower case in JS
* Improves documentation for page names based on [this article](https://community.fabric.microsoft.com/t5/Developer/set-active-page-in-report-with-JavaScript-API/m-p/93716)
* (Unrelated: Tweaks helper text for iframe edge app)
=> Improves usability of Edge App for reports

.github/workflows/deploy-clock-app-qc.yml, .github/workflows/deploy-clock-app.yml, .github/workflows/deploy-countdown-timer-qc.yml, .github/workflows/deploy-countdown-timer.yml, .github/workflows/deploy-iframe-qc.yml, .github/workflows/deploy-iframe.yml, .github/workflows/deploy-power-bi-qc.yml, .github/workflows/deploy-power-bi.yml, .github/workflows/deploy-rss-reader-qc.yml, .github/workflows/deploy-rss-reader.yml, .github/workflows/deploy-simple-message-app.yml, .github/workflows/deploy-weather-app-qc.yml, .github/workflows/deploy-weather-app.yml
New cli version 0.2.6 - for some commands(settings, secrets and promote) uses --installation-id instead of --app-id.
Updates that.
Though alternatively we could support --app-id in cli optionally for promote, but in that case we will omit checking settings, that are unset.
=> Updates: use installation_id instead of app_id for promote command

edge-apps/tfl-bus-status/README.md, edge-apps/tfl-bus-status/screenly.yml, edge-apps/tfl-bus-status/static/js/script.js
- Fixed setting secret value accessing issue with the secret variable. 
- Updated Installation guide with changes.
=> fix setting issue with secret

edge-apps/weather/index.html, edge-apps/weather/static/js/main.js
Edits:
- replaced `setTimeout`(`clearTimeout`) with `setInterval`. `setInterval` is executed once on app initialization. The issue: If there is an error before setTimeout, the page will no longer be refreshed.
- replaced the default `Waiting for Internet connection...` for all errors with the proper error messages. The issue: no matter what error it will always be "Waiting for Internet connection..." which compromises our devices
- added a global try/catch for the main function. The issue: because there is no way for customers to debug the weather app and report the issues, it should be a good solution **for now** before we add CLI logging.
Some screenshots with error messages:
=> Edits: for the weather Edge App

edge-apps/tfl-bus-status/index.html, edge-apps/tfl-bus-status/screenly.yml, edge-apps/tfl-bus-status/static/js/script.js
I added a Sentry DSN as a secret setting to manage and avoid throwing errors while testing locally and spamming the sentry.
=> Added a Sentry DSN as secret setting

edge-apps/clock/screenly.yml, edge-apps/clock/screenly_qc.yml, edge-apps/countdown-timer/screenly.yml, edge-apps/countdown-timer/screenly_qc.yml, edge-apps/rss-reader/screenly.yml, edge-apps/rss-reader/screenly_qc.yml, edge-apps/weather/screenly.yml, edge-apps/weather/screenly_qc.yml
Edge App settings to global:
- `enable_analytics`
- `tag_manager_id`
Note:
- `ready_for_rendering` will be deleted from the backend
=> Edits: some Edge App settings to global

edge-apps/clock/screenly_qc.yml
I set default locale as **en** for standard 
default_value: en``
=> Set Default locale in Clock App For Stability - QC yml only. 

edge-apps/google-calendar/screenly.yml, edge-apps/google-calendar/screenly_qc.yml
- Since users can now choose either `api` (Google OAuth credentials) or `ical` (iCal URL) for `calendar_source_type` (i.e., the data source, Google OAuth credentials must be optional.
- For instance, if users prefer to use just their Google Calendar iCal URL, they don't need to specify Google OAuth credentials like the client ID, the client secret, and the refresh token.
- Take note that the `refresh_token` is already an optional field.
=> feat: make Google Calendar app's OAuth credentials optional

.github/dependabot.yml
- Changed the frequency of doing Dependabot updates from `weekly` to `daily`
- Added rules for GitHub Actions
- Groups dependency updates according to ecosystem (e.g., `npm`, `pip`, `github-actions`)
___
Enhancement, Configuration changes
___
Increase Dependabot update frequency to daily
Add grouping for bun, pip, actions
Enable Dependabot for GitHub Actions
Apply groups with wildcard patterns
___
```mermaid
flowchart LR
A["Dependabot config"] -- "increase frequency" --> B["Daily updates"]
A -- "add groups" --> C["Ecosystem groups"]
A -- "new ecosystem" --> D["GitHub Actions"]
C -- "bun/pip/actions" --> E["Wildcard patterns (*)"]
```
<table><thead><tr><th></th><th align="left">Relevant …
=> chore(deps): increase freq of dependency updates; group deps into fewer PRs

edge-apps/google-calendar/src/components/WeeklyCalendarView.vue
Bug fix
___
Filter events to visible hour range
Exclude 12:00 AM only in afternoon view
Guard against empty time slots
Clear style cache on time slot changes
___
```mermaid
flowchart LR
events["Events list"] -- "iterate" --> filter["Filter by visible hours"]
timeSlots["Time slots"] -- "derive min/max hours" --> filter
currentHour["Current hour info"] -- "determine window" --> filter
filter -- "build keys day-hour" --> eventMap["Precomputed event map"]
events+timeSlots["Events or time slots change"] -- "clear" --> cache["Style cache"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details> …
=> fix: only add events that fall within the visible time range except hour 0

.github/dependabot.yml
- Dependabot is not creating Dependabot PRs for the Edge App Template lately.
- This PR configures `dependabot.yml` so that relevant PRs can be created again.
___
Enhancement, Configuration changes
___
- Reconfigure Dependabot ecosystems and scopes
- Add npm updates for edge app template
- Remove template path from bun directories
- Keep daily schedules and grouping
___
```mermaid
flowchart LR
A["Dependabot config"] -- "bun updates" --> B["edge-apps/*"]
A -- "remove" --> C[".bun-create path from bun"]
A -- "add npm updates" --> D["/edge-apps/.bun-create/edge-app-template"]
A -- "pip updates" --> E["/edge-apps/queue-management-system/server"]
```
<table><thead><tr><th></th><th align="left">Relevant …
=> chore: enable creation of Dependabot PRs for the Edge App template
