asset-metadata/README.md

Update metadata headers readme after a check with Grammarly.

Update README after Grammarly check

---

javascript-injectors/powerbi-signin-via-credentials.js

An issue:
- Sometimes the PowerBi page can be redirected to the select account page

Fix: powerbi signin via credentials script

---

javascript-injectors/powerbi-signin-via-cookies.js
javascript-injectors/powerbi-signin-via-credentials.js
javascript-injectors/screenly-signin-via-cookies.js
javascript-injectors/shiphero-signin-via-credentials.js
javascript-injectors/tableau-via-cookies.js

Ref: https://github.com/Screenly/playground/pull/17

Fix: javascript-injectors lint

---

javascript-injectors/README.md

Updates documentation for JavaScript Injector.

Fixes documentation

---

.github/workflows/deploy-asset-metadata.yml
asset-metadata/app.yaml
asset-metadata/src/static/style.css

Changes to deploy actions

---

.github/workflows/deploy-asset-metadata.yml

Fixes app.yml path

---

.github/workflows/deploy-asset-metadata.yml
asset-metadata/app.yaml

Removes $, add _VAL to template string

Replaces API_KEY placeholder

---

README.md
bootstrap/README.md

Tweaks documentation for Bootstrap theme and front page.

Tweaks documentation

---

edge-apps/weather/index.html
edge-apps/weather/screenly.yml

Tweak the weather app's settings.

---

edge-apps/weather/index.html
edge-apps/weather/screenly.yml
edge-apps/weather/static/styles/background.css
edge-apps/weather/static/styles/main.css

Fixes weather app

---

edge-apps/rss-reader/index.html
edge-apps/rss-reader/screenly.yml
edge-apps/rss-reader/static/js/main.js

Fixes issue with CORS proxy and display in RSS reader app

---

.github/workflows/deploy-clock-app-qc.yml
.github/workflows/deploy-clock-app.yml

* Maps Clock to QC account.
* Manual trigger deploy to production.

Tries to fix clock app

---

.github/workflows/deploy-countdown-timer-qc.yml
.github/workflows/deploy-countdown-timer.yml

Added countdown timer deploy and QC yaml files

---

.github/workflows/deploy-power-bi.yml

Edits:
- Replaced a wrong api_token secret

Fix: .github/workflows/deploy-power-bi.yml

---

helpers/tfl/bus-stop-lookup/index.html
helpers/tfl/bus-stop-lookup/script.js

Primitive TFL Bus Stop lookup based on official CSV file.

Adds basic TFL Bus Stop Lookup site

---

.github/workflows/deploy-tfl-bus-status-qc.yml
.github/workflows/deploy-tfl-bus-status.yml

- Added tfl-bus-status app deploy files
- Added tfl-bus-status QC app deploy files.

Added tfl-bus-status app deploy and QC CI files 

---

edge-apps/tfl-bus-status/screenly.yml

```
app_id:
installation_id:
user_version: v1.0.0
```
Added the installation id field

Added installation id field  on the TFL edge app .yml

---

edge-apps/powerbi/screenly.yml
edge-apps/powerbi/screenly_qc.yml

Replaces: old style ready_signal with new one for power_bi

Replaces: old style ready_signal with new one for power_bi

---

edge-apps/tfl-bus-status/screenly.yml
edge-apps/tfl-bus-status/screenly_qc.yml

Replaces: old style ready_signal with new one for tfl

Replaces: old style ready_signal with new one for tfl

---

.github/workflows/deploy-power-bi-qc.yml

Fix: adds missing MANIFEST_FILE_NAME for qc

Fix: adds missing MANIFEST_FILE_NAME for qc

---

.github/workflows/deploy-countdown-timer.yml

As per Vlad's comment on T8985, I added debug log option on CI build.

Added Debug log for the timer deploy files

---

edge-apps/clock/screenly_qc.yml

fix qc clock app icon

---

.github/workflows/deploy-simple-message-app-qc.yml

Fix QC App Token Path 

---

edge-apps/rss-reader/index.html
edge-apps/rss-reader/screenly_qc.yml
edge-apps/rss-reader/static/css/style.css
edge-apps/rss-reader/static/js/main.js

Fix rss reader app and added Sentry Config. 

---

edge-apps/helpers/tfl/bus-stop-lookup/index.html
edge-apps/helpers/tfl/bus-stop-lookup/script.js
edge-apps/helpers/tfl/bus-stop-lookup/style.css

This PR improves the TFL Bus Stop Lookup tool with performance optimizations and enhanced user experience. Fixes - https://github.com/Screenly/Playground/issues/223 
- Added pagination (100 items per page) for faster loading
- Implemented clickable bus stop codes with copy feature
- Added loading indicators and error handling
- Created A-Z filters and pattern filters for quicker navigation
- Fixed UI breaking on refresh with better element handling
- Enhanced design with animations and mobile responsiveness
- Take time to load 
- Slow in searching for STOP ID. 
- Enhanced for improved search and experience

Bus Stop Lookup: Performance Optimizations and Copy Feature 

---

.github/workflows/initialize-app.yml
.github/workflows/update-edge-app.yml

**Now**
___
Other
___
- Restrict initialize-app dispatch to master branch
- Restrict update-edge-app dispatch to master branch
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>initialize-app.yml</strong><dd><code>Add branch filter to initialize-app workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/initialize-app.yml
<ul><li>Added <code>branches: [master]</code> under <code>workflow_dispatch</code><br> <li> Restricted manual triggers to master branch</ul>
</details>
</td>
<td><a …

Restrict Edge App Init and Update Workflow to Master Branch

---

README.md
edge-apps/.bun-create/edge-app-template/package.json

When `bun run create` is run, it will generate the following message at the end (instead of the default one):
```plaintext
Dependencies were installed automatically.
Created edge-app-template project successfully
cd sample-app-1
bun run build:dev # On one terminal session
bun run dev # On another terminal session
```
This change will help prevent confusion among users. Having the welcome message just show `bun dev` will prompt them to run `bun dev`, which, when run alone, won't work.
___
Enhancement, Documentation
___
- Update README get-started commands for Edge App
- Replace single `bun dev` with two commands
- Add `bun-create.start` script in template `package.json`
- Guide separate sessions for build and dev
___ …

chore: update welcome message shown when an Edge App is created via the Vue-based template

---

.github/workflows/test-edge-app-template-generation.yml

Tests, Enhancement
___
- Add CI workflow for Edge App template
- Install Bun and Playwright dependencies
- Run template generation, build, tests
- Upload report and cleanup
___
```mermaid
flowchart LR
A["Trigger (PR, push, manual)"] --> B["Checkout code"]
B --> C["Setup Bun"]
C --> D["Generate Edge App Template"]
D --> E["Build and bundle app"]
E --> F["Run unit tests"]
F --> G["Install Playwright and run E2E"]
G --> H["Upload Playwright report"]
H --> I["Cleanup test app"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>test-edge-app-template-generation.yml</strong><dd><code>Add Edge App template …

chore(ci): create a new CI workflow that tests Edge App generation

---

.github/dependabot.yml

- Fixes #328
___
Enhancement, Other
___
- Add Dependabot config for npm and pip
- Scan Edge Apps packages recursively via glob
- Weekly update schedule for dependencies
- Configure server path for Python updates
___
```mermaid
flowchart LR
A["Dependabot config"] -- "adds" --> B["npm updates (edge-apps/*)"]
A -- "adds" --> C["pip updates (/edge-apps/.../server)"]
B -- "scheduled weekly" --> D["Automated PRs"]
C -- "scheduled weekly" --> D
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>dependabot.yml</strong><dd><code>Add Dependabot v2 config for npm and pip</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

chore(ci): create a `dependabot.yml` file

---

edge-apps/blueprint/ts/components/AnalogClock.vue

- The analog clock component stutters when used in an Edge App that involves fetching of data via cloud (e.g., a Google Calendar Edge App).
- The second hand of the analog clock appears like it doesn't tick on time (i.e., every second).
- We replaced calls to [`setInterval`](https://developer.mozilla.org/en-US/docs/Web/API/Window/setInterval) and `clearInterval` with [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame) and `clearAnimationFrame`.
___
Enhancement
___
Replace intervals with requestAnimationFrame
Throttle updates to once per second
Initialize timing with performance.now
Add CSS hints for smoother transforms
___
```mermaid
flowchart LR
INIT["Mount: set current time, init lastUpdateTime"] -- "start rAF" --> …
```

chore: optimize the analog clock component

---

.github/workflows/linter.yml

- Replaced `github/super-linter@v7` with `super-linter/super-linter@v8`
- Disabled validations for Checkov, Vue, and JSCPD
___
Enhancement, Configuration changes
___
- Upgrade to `super-linter` v8 action
- Disable Vue and Vue Prettier validations
- Disable JSCPD and Checkov checks
- Keep selective TypeScript validations disabled
___
```mermaid
flowchart LR
A["GitHub Actions Workflow"] -- "uses" --> B["super-linter/super-linter@v8"]
B -- "env updates" --> C["Disable Vue & Vue Prettier"]
B -- "env updates" --> D["Disable JSCPD"]
B -- "env updates" --> E["Disable Checkov"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td> …

chore(ci): modify `super-linter` settings

---

.github/workflows/linter.yml
.github/workflows/update-edge-app.yml

Enhancement
___
- Add delete missing settings input
- Pass flag to deploy CLI command
- Extend workflow to toggle cleanup behavior
___
```mermaid
flowchart LR
input["New input: delete_missing_settings"] --> stepSetEnv["Job uses input in deploy step"]
stepSetEnv --> cli["CLI command edge-app deploy"]
input --> cli
cli -- "--delete-missing-settings=<bool>" --> deploy["Deploy Edge App with cleanup option"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>update-edge-app.yml</strong><dd><code>Add cleanup toggle to Edge App deploy workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

chore(ci): add support for deleting missing settings when updating Edge Apps

---

edge-apps/powerbi/screenly_qc.yml

Enhancement, Documentation
___
- Add Power BI QC app manifest
- Define secure settings and help schemas
- Support embed token and URL inputs
- Optional error display for debugging
___
```mermaid
flowchart LR
Manifest["Power BI QC manifest_v1"] --> Settings["Settings definitions"]
Settings --> EmbedURL["Required: embed_url (oauth schema)"]
Settings --> EmbedToken["Optional: embed_token (secret oauth)"]
Settings --> DisplayErrors["Optional: display_errors (boolean)"]
Manifest --> Metadata["Icon, author, ready_signal, description"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details> …

Add Power BI QC manifest file

---

edge-apps/bamboo-hr-app/screenly.yml
edge-apps/bamboo-hr-app/screenly_qc.yml

- Gave a proper description for the new BambooHR app
- Added an Edge App ID for `screenly_qc.yml`
___
Enhancement, Documentation
___
- Add meaningful BambooHR app description
- Introduce staging manifest `id`
- Update QC manifest metadata
___
```mermaid
flowchart LR
A["BambooHR manifests"] -- "add description" --> B["screenly.yml"]
A -- "add id + description" --> C["screenly_qc.yml"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>screenly.yml</strong><dd><code>Add meaningful description to production manifest</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

chore: update BambooHR app's manifest description; add app ID for staging manifest file
